#baseURL = "https:\\riganti.com.au"
languageCode = "en-us"
title = "Mark Riganti's Project Website"
theme = "meghna-markmod"
summaryLength = 10

# Menu
[menu]

    [[menu.nav]]
    name = "Projects"
    URL = "portfolio"
    weight = 2

# Site params
[params]
home= "Home"
logo = "images/logo.png"
custom_css = ["css/custom.css"]

# Meta data
description = "Mark Riganti's Project Website"
author = "PooCorp Industries"

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/bgc.jpg"
    logo = "images/logo.png"
    heading = "Code. Cad. Carve. Create."
    content= "Mark Riganti's Project log site."
    btn = true
    btnText="Projects"
    btnURL="#portfolio"

    # Projects Section
    [params.portfolio]
    enable = true
    bgImage = "images/bgc.jpg"

    # footer
    [params.footer]
        copyright = "PooCorp Industries"
        copyrightURL = "PooCorp.com"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-github"
        url = "https://github.com/OmNomNomagon"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-github"
        url = "https://www.thingiverse.com/OmNomNomagon/about"