#baseURL = "https:\\riganti.com.au"
languageCode = "en-us"
title = "Mark Riganti's Project Website"
theme = "meghna-hugo"

# Menu
[menu]

    [[menu.nav]]
    name = "Projects"
    URL = "portfolio"
    weight = 2

    [[menu.nav]]
    name = "About me"
    URL = "about"
    weight = 4
	
    [[menu.nav]]
    name = "Contact"
    URL = "contact-me"
    weight = 8
	
# Site params
[params]
home= "Home"
logo = "images/logo.png"
# Meta data
description = "HTML5 Template"
author = "PooCorp Industries"

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/bgc.jpg"
    logo = "images/logo.png"
    heading = "Code. Cad. Carve. Create."
    content= "Mark Riganti's Project log site."
    btn = true
    btnText="Projects"
    btnURL="#portfolio"

    #Projects Section
    [params.portfolio]
    enable = true

    # footer
    [params.footer]
        copyright = "PooCorp Industries"
        copyrightURL = "PooCorp.com"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-github"
        url = "https://github.com/OmNomNomagon"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-github"
        url = "https://www.thingiverse.com/OmNomNomagon/about"